services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: on-failure
    network_mode: "host"
    volumes:
      - ./conf.d:/etc/nginx/conf.d:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
